# Generated by Django 3.0.8 on 2020-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20200712_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
