# Generated by Django 3.0.8 on 2020-07-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_site_is_mvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='is_mvp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
